version: "4.5"
services:
  bot:
    container_name: chatbot-tg
    build:
      context: .
    env_file:
      - .env
    ports:
      - "80:3000"
    volumes:
      - botdata:/app/data

volumes:
  botdata:
